### ISSUE TITLE
my_each_spec.rb - line 15-19

### ISSUE THREAD

**Issue by eric-an** [learn-co-curriculum/my-each#22]
If I'm understanding this right, in the below code, the expectation should be corrected to: expect(contents).to_not include("while" && "puts")

```
  it "does not call on while or puts" do 
    file = File.read('./my_each.rb')
    contents = file.split(" ")
    expect(contents).to_not include("while" || "puts")
  end
```

I apologize if I'm wrong. Thanks for the awesome lessons!

**Comment by AnnJohn** [comment]
Assigned to @MsUzoAgu

**Comment by AnnJohn** [comment]
Hi @eric-an the spec is correct because the contents should not include while or puts, so only one of those conditions needs to be met. Using && means that both would have to be met which isn't what we're looking for. Thanks!!

**Comment by MsUzoAgu** [comment]
@eric-an: we corrected to spec file to indicate that only `puts` should not be included in the contents of `my_each` method. `While` can be included in `my_each` method definition because we need to perform an action (loop/iterate) over a collection only under certain conditions. `While` is one of the methods that enables us to do this. 

Thanks for pointing out the discrepancy.
