### ISSUE TITLE
Missing Content?

### ISSUE THREAD

**Issue by yancann** [learn-co-curriculum/my-each#24]
I feel like I'm going crazy— the lab reads "Now that you know how the yield method works, try to write..." but no previous lesson has covered the yield method. Is there missing content or is this a sink or swim situation?

**Comment by vicfriedman** [comment]
Hey, @yancann,

The piece of content that precedes this lab is https://github.com/learn-co-students/yield-and-blocks-v-000, which does cover `yield`. Because of this, I'm going to go ahead and close this issue. Please feel free to comment back with more information if you feel like this is still an issue.
